spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:jobs_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/jobs_db
    password: dominic
    username: password

# Actuator
management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
  endpoints:
    web:
      exposure:
        include: loggers, info, health, metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: Job App
    description: Job app build by Domie
    version: 1.0.0

